// Input limits for the public demo topic editor; no provider is configured.
export const HOSTED_CONFIG = {
 GROUP_CODE_LENGTH: 6, MAX_GROUP_NAME_CHARS: 80, MAX_DISPLAY_NAME_CHARS: 30, MAX_MEMBERS: 40,
 DEFAULT_ARGUMENT_CHAR_LIMIT: 2000, MAX_ARGUMENT_CHAR_LIMIT: 5000,
 MAX_QUESTION_CHARS: 1000, MAX_POSITION_CHARS: 1000, MAX_ATTRIBUTION_CHARS: 120,
 MAX_SOURCES: 10, MAX_SOURCE_LABEL_CHARS: 160, MAX_SOURCE_CHARS: 4000, MAX_TOTAL_SOURCE_CHARS: 16000,
} as const;
