import { useMemo, useState, type ReactNode } from 'react';
import { TopicEditor } from '../hosted/TopicEditor';
import type { HostedTopicInput } from '../shared/hostedTypes';

type Format = 'single' | 'tournament';
type Timer = 'timed' | 'untimed';
const exerciseTitle = 'Ship Friday or fix first?';
const caseFacts = 'The team publicly promised Friday. The bug is recoverable but affects about 1 in 20 first-time setups. Support has two people. The fix is expected Monday. No other facts should be assumed.';
const opposingArgument = 'Delay until Monday. A first experience is hard to recover, and two support people may not be enough if several affected customers need help together.';
const defaultTopic: HostedTopicInput = {
 type: 'twoPosition', question: 'A fictional software team promised a Friday release. A recoverable bug affects about 1 in 20 first-time setups. Support has two people, and a fix can be ready Monday. What should the team do?',
 positionA: { text: 'Release Friday with a clear workaround, active monitoring, and support ready to respond.', attribution: 'Position A' },
 positionB: { text: 'Delay until Monday, fix the bug, and protect customers’ first experience.', attribution: 'Position B' },
 sources: [{ id: 'fictional-case-facts', label: 'Fictional case facts', text: caseFacts }],
};
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character] ?? character)); }
function Exercise({ topic }: { topic: HostedTopicInput }) { const isExample = JSON.stringify(topic) === JSON.stringify(defaultTopic); return <div className="demo-exercise"><span className="demo-pill">Fictional practice exercise</span><h2>{isExample ? exerciseTitle : 'Your custom practice'}</h2><p>{topic.question}</p><div className="demo-positions"><div><b>{topic.positionA.attribution || 'Position A'}</b><span>{topic.positionA.text}</span></div><div><b>{topic.positionB.attribution || 'Position B'}</b><span>{topic.positionB.text}</span></div></div><details className="demo-see-other"><summary>Sources for this exercise</summary>{topic.sources.length ? topic.sources.map((source) => <p key={source.id}><b>{source.label || 'Source'}:</b> {source.text}</p>) : <p>No sources added. Source use will not be scored.</p>}</details></div>; }
function Page({ headline, children }: { headline: string; children: ReactNode }) { return <main id="practice-content" className="demo-main"><div className="hosted-page-head"><div><p className="hosted-kicker">Public demo · fictional data only</p><h1>{headline}</h1></div></div>{children}</main>; }
function Back({ go }: { go: (route: string) => void }) { return <button className="quiet hosted-back" onClick={() => go('groups')}>← Back to groups</button>; }

export function PracticeDemo({ screen, onNavigate }: { screen: string; onNavigate: (screen: string) => void }) {
 const [signedIn, setSignedIn] = useState(false); const [groupName, setGroupName] = useState('Friday Studio'); const [joinCode, setJoinCode] = useState('FRIDAY'); const [name, setName] = useState('Maya Chen'); const [joinError, setJoinError] = useState('');
 const [argument, setArgument] = useState('Release Friday, with the workaround on the setup screen and the support team ready to respond. A one-in-twenty issue is recoverable, and keeping a public commitment can build trust when the risk is named plainly.'); const [submitted, setSubmitted] = useState(false); const [format, setFormat] = useState<Format>('single'); const [timer, setTimer] = useState<Timer>('timed');
 const [topic, setTopic] = useState<HostedTopicInput>(defaultTopic); const [sessionDeleted, setSessionDeleted] = useState(false); const [simulated, setSimulated] = useState(false); const [showFeedback, setShowFeedback] = useState(false); const [reflection, setReflection] = useState('I had given too little weight to how first-time friction can shape a customer’s confidence.'); const [reflectionSaved, setReflectionSaved] = useState(false);
 const go = (route: string) => onNavigate(route); const current = screen || 'groups'; const customTopic = JSON.stringify(topic) !== JSON.stringify(defaultTopic); const headline = useMemo(() => ({ groups: 'Practice with your group', signin: 'Host a group', group: groupName, topics: 'Topic bank', setup: 'Set up a practice', join: 'Join a group', waiting: 'You are in', writing: 'Make your case', submitted: 'Argument submitted', feedback: 'Round feedback', monitor: 'Session monitor', between: 'Tournament round complete', results: 'Session results', privacy: 'Demo privacy note', deleted: 'Fictional session deleted' }[current] ?? 'Practice with your group'), [current, groupName]);
 function resetPractice() { setGroupName('Friday Studio'); setJoinCode('FRIDAY'); setName('Maya Chen'); setJoinError(''); setArgument(''); setSubmitted(false); setFormat('single'); setTimer('timed'); setTopic(defaultTopic); setSessionDeleted(false); setSimulated(false); setShowFeedback(false); setReflection(''); setReflectionSaved(false); setSignedIn(false); go('groups'); }
 function submitJoin() { if (joinCode.trim().toUpperCase() !== 'FRIDAY') { setJoinError('For this walkthrough, use the fictional code FRIDAY.'); return; } if (!name.trim()) { setJoinError('Enter a display name to continue.'); return; } setJoinError(''); go('waiting'); }
 function downloadRecord() { const champion = format === 'tournament' ? '<p><strong>Fictional champion:</strong> Maya Chen</p>' : ''; const html = `<!doctype html><html lang="en"><meta charset="utf-8"><title>Fictional Verdict record</title><body><h1>Fictional Verdict session record</h1><p><strong>Group:</strong> ${escapeHtml(groupName)}<br><strong>Format:</strong> ${format === 'tournament' ? 'Tournament' : 'Single round'}<br><strong>Exercise:</strong> ${escapeHtml(topic.question)}</p>${champion}<h2>Arguments</h2><p><strong>${escapeHtml(name || 'Maya Chen')} · ${escapeHtml(topic.positionA.text)}</strong><br>${escapeHtml(argument || '(No argument submitted)')}</p><p><strong>Jon Bell · ${escapeHtml(topic.positionB.text)}</strong><br>${escapeHtml(opposingArgument)}</p><h2>Fixed fictional feedback</h2><p>This illustration does not evaluate typed arguments, including any edits to the topic.</p><ul><li>Claim clarity: 8/10</li><li>Source use: 7/10</li><li>Response to other side: 6/10</li><li>Internal consistency: 8/10</li></ul><p>Names, arguments, scores, and outcome are fictional demo data.</p></body></html>`; const url = URL.createObjectURL(new Blob([html], { type: 'text/html;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'fictional-verdict-record.html'; document.body.appendChild(anchor); anchor.click(); anchor.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
 function deleteFictionalSession() { setArgument(''); setSubmitted(false); setReflection(''); setReflectionSaved(false); setSimulated(false); setShowFeedback(false); setSessionDeleted(true); go('deleted'); }
 const content = (() => {
  if (current === 'signin') return <section className="hosted-panel demo-narrow"><h2>Try the host view</h2><p>This button only simulates sign-in. It does not contact Google or create an account.</p><button className="primary huge" onClick={() => { setSignedIn(true); go('groups'); }}>Continue as demo host</button><button className="quiet huge" onClick={() => go('groups')}>Return to demo</button></section>;
  if (current === 'privacy') return <section className="hosted-panel demo-narrow"><h2>What this demo does</h2><p>This public walkthrough runs only in this browser tab. It does not send your name, writing, or click activity to Verdict, Google, or a third party.</p><h3>How the live group product handles records</h3><p>Group-session records are retained for up to 30 days, then deleted. A host can request earlier deletion. This demo has no account or server record: its fictional session state resets when you use Reset demo or close the tab.</p><button className="secondary" onClick={() => go('join')}>Read the join notice</button></section>;
  if (current === 'join') return <section className="hosted-panel demo-narrow"><h2>Enter the group code</h2><label className="field">Group code<input className="participant-code-input" value={joinCode} onChange={(event) => { setJoinCode(event.target.value.toUpperCase()); setJoinError(''); }} maxLength={6} /></label><label className="field">Display name<input value={name} onChange={(event) => { setName(event.target.value); setJoinError(''); }} /></label>{joinError && <p className="demo-error" role="alert">{joinError}</p>}<p className="demo-notice"><b>Demo notice:</b> This is a fictional browser-only walkthrough. Nothing entered here is transmitted or stored after the session resets.</p><button className="primary huge" onClick={submitJoin}>Join {groupName}</button></section>;
  if (sessionDeleted && ['waiting', 'writing', 'submitted', 'feedback', 'monitor', 'between', 'results'].includes(current)) return <section className="hosted-panel demo-narrow"><span className="demo-status">Session deleted</span><h2>This fictional session is no longer available.</h2><p>Its local arguments and reflection were cleared. Start a fresh demo session to continue.</p><button className="primary huge" onClick={resetPractice}>Start a fresh demo session</button><button className="quiet huge" onClick={() => go('privacy')}>Read the data note</button></section>;
  if (current === 'waiting') return <section className="hosted-panel demo-narrow"><span className="demo-status">Waiting for the host</span><h2>Welcome, {name || 'participant'}</h2><p>You will receive an assigned position when the fictional host starts the exercise.</p><Exercise topic={topic} /><button className="primary huge" onClick={() => go('writing')}>Simulate assignment</button><button className="quiet huge" onClick={() => go('join')}>Change display name</button></section>;
  if (current === 'writing') return <section className="hosted-panel"><div className="demo-round-head"><div><span className="demo-status">Your assignment</span><h2>Position A · {topic.positionA.text}</h2></div>{timer === 'timed' && <span className="demo-clock"><small>Simulated timer, paused</small><b>04:28</b></span>}</div><Exercise topic={topic} /><label className="field">Your argument<textarea aria-label="Your argument" value={argument} onChange={(event) => setArgument(event.target.value)} rows={7} maxLength={1200} /></label><p className="muted">{argument.length}/1200 characters · Your writing remains in this browser demo.</p><button className="primary" onClick={() => { setSubmitted(true); go('submitted'); }}>Submit argument</button><button className="quiet" onClick={() => go('waiting')}>Return to waiting room</button></section>;
  if (current === 'submitted') return <section className="hosted-panel demo-narrow"><span className="demo-status">Submitted</span><h2>Your case is locked for this fictional round.</h2><p>The host can simulate another submission and sample feedback. The feedback in this demo is fixed example copy; it does not evaluate the argument you typed.</p><button className="primary huge" onClick={() => go('feedback')}>View sample feedback</button><button className="quiet huge" onClick={() => go('writing')}>Return to draft</button></section>;
  if (current === 'feedback') return <section className="hosted-panel"><span className="demo-status">Sample round feedback</span><h2>{customTopic ? 'Separate sample: Ship Friday or fix first?' : 'Release Friday advances'}</h2><p className="demo-notice">Fixed fictional example. This feedback is not generated from or evaluating your typed argument{customTopic ? ' or your custom topic' : ''}.</p><button className="demo-disclosure" onClick={() => setShowFeedback((open) => !open)} aria-expanded={showFeedback}>Scores and reasoning <span>{showFeedback ? '−' : '+'}</span></button>{showFeedback && <div className="demo-feedback"><div className="demo-score-grid"><span>Claim clarity <b>8/10</b></span><span>Source use <b>7/10</b></span><span>Response to other side <b>6/10</b></span><span>Internal consistency <b>8/10</b></span></div><p>The fixed illustration makes a clear tradeoff between honoring a public commitment and reducing first-time friction. It is strongest when it names the monitoring condition.</p></div>}<details className="demo-see-other"><summary>Review the arguments</summary><p><b>Your draft in this browser:</b> {argument || '(No argument entered)'}</p><p><b>Fictional opposing argument:</b> {opposingArgument}</p></details><details className="demo-see-other"><summary>See the other perspective</summary><p>Delay advocates can reasonably argue that a first experience is unusually hard to recover, and that two support people may not be enough when the affected users need help at once.</p></details><label className="field">Reflection<textarea aria-label="Reflection" value={reflection} onChange={(event) => { setReflection(event.target.value); setReflectionSaved(false); }} rows={4} /></label><button className="secondary" onClick={() => setReflectionSaved(true)}>{reflectionSaved ? 'Reflection saved in this demo' : 'Save reflection'}</button><button className="quiet" onClick={() => go('results')}>See session results</button></section>;
  if (current === 'monitor') return <section className="hosted-panel"><div className="hosted-panel-head"><div><h2>{topic.question}</h2><p>4 fictional participants · {format === 'single' ? 'Single round' : 'Tournament'} · {timer === 'timed' ? '5 minutes' : 'Untimed'}</p></div><span className="demo-status">Writing</span></div><div className="demo-progress"><span style={{ width: simulated ? '100%' : submitted ? '50%' : '25%' }} /></div><p>{simulated ? '4 of 4 sample arguments submitted across two pairs.' : submitted ? '2 of 4 sample arguments submitted.' : '1 of 4 sample arguments submitted.'}</p><div className="hosted-action-row"><button className="secondary" onClick={() => setSimulated(true)}>Simulate submissions</button><button className="primary" onClick={() => go(format === 'tournament' ? 'between' : 'results')}>Sample judging</button><button className="quiet" onClick={() => go('setup')}>Edit next session</button></div><h3>Roster and pairs</h3><div className="hosted-roster"><div className="hosted-roster-row"><span><strong>Maya Chen</strong><small>{submitted || simulated ? 'submitted' : 'writing'} · Position A</small></span><b>Pair 1</b></div><div className="hosted-roster-row"><span><strong>Jon Bell</strong><small>{simulated ? 'submitted' : 'writing'} · Position B</small></span><b>Pair 1</b></div><div className="hosted-roster-row"><span><strong>Rina Patel</strong><small>{simulated ? 'submitted' : 'waiting'} · Position A</small></span><b>Pair 2</b></div><div className="hosted-roster-row"><span><strong>Ari Stone</strong><small>{simulated ? 'submitted' : 'waiting'} · Position B</small></span><b>Pair 2</b></div></div></section>;
  if (current === 'between') return <section className="hosted-panel demo-narrow"><span className="demo-status">Semifinals complete</span><h2>Two fictional finalists are ready.</h2><p>Maya Chen and Rina Patel advance to the final round. Their names and outcomes are preset examples.</p><button className="primary huge" onClick={() => { setFormat('tournament'); go('results'); }}>Finish fictional tournament</button><button className="quiet huge" onClick={() => go('monitor')}>Return to monitor</button></section>;
  if (current === 'results') return <section className="hosted-panel"><div className="hosted-panel-head"><div><h2>{format === 'tournament' ? 'Tournament complete' : 'Single round complete'}</h2><p>Fictional session record · {topic.question}</p></div>{format === 'tournament' && <span className="demo-champion">Champion: Maya Chen</span>}</div><div className="demo-results"><div className="demo-result-row"><b>Maya Chen</b><span>Position A · Pair 1</span><strong>{format === 'tournament' ? 'Champion' : 'Sample winner'}</strong></div><div className="demo-result-row"><b>Jon Bell</b><span>Position B · Pair 1</span><strong>Sample feedback</strong></div><div className="demo-result-row"><b>Rina Patel</b><span>{format === 'tournament' ? 'Finalist' : 'Position A · Pair 2'}</span><strong>{format === 'tournament' ? 'Completed' : 'Sample winner'}</strong></div><div className="demo-result-row"><b>Ari Stone</b><span>{format === 'tournament' ? 'Semifinalist' : 'Position B · Pair 2'}</span><strong>{format === 'tournament' ? 'Completed' : 'Sample feedback'}</strong></div></div><p className="demo-notice">Names, outcomes, and feedback above are fictional examples. If you edited the topic, the sample outcome is still preset and is not an evaluation of that edit.</p><button className="secondary" onClick={downloadRecord}>Download fictional HTML record</button><button className="primary" onClick={() => go('setup')}>Start another fictional session</button><button className="quiet" onClick={deleteFictionalSession}>Delete this fictional session</button><button className="quiet" onClick={() => go('group')}>Return to group</button></section>;
  if (current === 'deleted') return <section className="hosted-panel demo-narrow"><span className="demo-status">Deleted from this browser demo</span><h2>The fictional session has been cleared.</h2><p>In the live group product, a host can request earlier deletion before the 30-day retention limit. Here, the local argument and reflection were cleared immediately.</p><button className="primary huge" onClick={resetPractice}>Start a fresh demo session</button><button className="quiet huge" onClick={() => go('privacy')}>Read the data note</button></section>;
  if (current === 'topics') return <><Back go={go} /><section className="hosted-panel"><div className="hosted-panel-head"><div><h2>Topic bank</h2><p>Edit this fictional topic and its optional sources. The selected topic follows the participant, monitor, results, and export views.</p></div><button className="secondary" onClick={() => setTopic(defaultTopic)}>Restore example</button></div><TopicEditor value={topic} onChange={setTopic} /><button className="primary" onClick={() => go('setup')}>Use this fictional topic</button></section></>;
  if (current === 'setup') return <><Back go={go} /><section className="hosted-panel demo-setup"><h2>Choose an exercise</h2><Exercise topic={topic} /><fieldset className="hosted-segmented"><legend>Format</legend><button className={format === 'single' ? 'active' : ''} onClick={() => setFormat('single')}>Single round</button><button className={format === 'tournament' ? 'active' : ''} onClick={() => setFormat('tournament')}>Tournament</button></fieldset><fieldset className="hosted-segmented"><legend>Writing time</legend><button className={timer === 'timed' ? 'active' : ''} onClick={() => setTimer('timed')}>Timed · 5 min</button><button className={timer === 'untimed' ? 'active' : ''} onClick={() => setTimer('untimed')}>Untimed</button></fieldset><p className="demo-notice">Participants are assigned one of the two stated positions and write their own arguments.</p><button className="primary huge" onClick={() => { setSessionDeleted(false); go('monitor'); }}>Start fictional session</button></section></>;
  if (current === 'group') return <><Back go={go} /><section className="hosted-dashboard-grid hosted-group-grid"><div className="hosted-panel"><h2>Group details</h2><label className="field">Group name<input value={groupName} onChange={(event) => setGroupName(event.target.value)} /></label><label className="field">Join code<input value="FRIDAY" readOnly className="participant-code-input" /></label><button className="secondary" onClick={() => go('setup')}>Plan a practice</button></div><div className="hosted-panel"><h2>Roster</h2><div className="hosted-roster"><div className="hosted-roster-row"><strong>Maya Chen</strong><span className="demo-status">Ready</span></div><div className="hosted-roster-row"><strong>Jon Bell</strong><span className="demo-status">Ready</span></div><div className="hosted-roster-row"><strong>Rina Patel</strong><span className="demo-status">Joined</span></div><div className="hosted-roster-row"><strong>Ari Stone</strong><span className="demo-status">Joined</span></div></div><button className="quiet" onClick={() => go('join')}>Preview participant join</button></div></section></>;
  return <section className="hosted-dashboard-grid"><div className="hosted-panel"><p className="hosted-kicker">Host view</p><h2>{signedIn ? 'Demo host: Jordan' : 'Explore the host workspace'}</h2><p>Create a group, see a roster, and run a structured two-person practice. All names and outcomes below are fictional.</p><button className="primary" onClick={() => signedIn ? go('group') : go('signin')}>{signedIn ? 'Open Friday Studio' : 'Simulate host sign-in'}</button><button className="quiet" onClick={() => { setGroupName('New practice group'); go('group'); }}>Create a fictional group</button><button className="quiet" onClick={() => go('topics')}>Browse topic bank</button></div><div className="hosted-panel"><p className="hosted-kicker">Participant view</p><h2>Join a practice</h2><p>Try the participant flow, from the privacy notice through feedback and reflection.</p><button className="secondary" onClick={() => go('join')}>Enter fictional code</button><button className="quiet" onClick={() => go('privacy')}>How this demo handles data</button></div><section className="hosted-panel"><h2>Friday Studio</h2><p>4 fictional participants · Join code <b className="hosted-code-mini">FRIDAY</b></p><button className="secondary" onClick={() => { setGroupName('Friday Studio'); go('group'); }}>View group dashboard</button><button className="primary" onClick={() => go('setup')}>Set up practice</button></section></section>;
 })();
 return <Page headline={headline}>{content}</Page>;
}
